# Site settings
title: chopys blog
email: cs.chopy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  automotive software engineer - tech - gaming nerd
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://chopyy.github.io" # the base hostname & protocol for your site

github_username:  chopyy

# A profile picture for the index page
avatar: https://avatars3.githubusercontent.com/u/3890882?v=3&s=460

# Build settings
markdown: kramdown
highlighter: rouge
mathjax: true
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

paginate: 5

plugins:
  - jekyll-seo-tag
